// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zihzqgildeedmgoiuewe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppaHpxZ2lsZGVlZG1nb2l1ZXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODU2ODIsImV4cCI6MjA2OTg2MTY4Mn0.K9yJi7LIAtYQaMB-kxywsNL3adZBN4zhNoGNxcYTBYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});